# -*- coding: utf-8 -*-
"""MLOps_Log_Reg_IrisData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvGivvuVPyceiOpDvrzY6rbw4R5H7qQr
"""

import pandas as pd

df = pd.read_csv('/content/Iris.csv')

df.sample(5)

X = df[["SepalLengthCm","SepalWidthCm","PetalWidthCm"]]   # input features
Y = df["Species"] # taget variable

from sklearn.linear_model import LogisticRegression

#step:1 initialise the class method
model = LogisticRegression()

#step:2 train the model with historical training data
model.fit(X,Y)

#step:3 predicting unknow value
X_known= [5.5,4.6,1,2.4]

model.predict([X_known])